apiVersion: apps/v1
kind: Deployment
metadata:
  name: supermario-deployment
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: supermario
  template:
    metadata:
      labels:
        app: supermario
    spec:
      containers:
      - image: bharathshetty4/supermario:latest
        name: supermario-container
        ports:
        - containerPort: 80
