apiVersion: apps/v1
kind: Deployment
metadata:
  name: mariodemo-deployment
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: mariodemo
  template:
    metadata:
      labels:
        app: mariodemo
    spec:
      containers:
      - image: asecurityguru/mariodemo:v1.0
        name: supermario-container
        ports:
        - containerPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: supermario-service
spec:
  selector:
    app: mariodemo
  ports:
  - protocol: TCP
    port: 8600  # <-- Change this line to your desired port
    targetPort: 8080
  type: LoadBalancer
